import { Plugin } from '@/types/plugin'

export const mockPlugins: Plugin[] = [
  {
    id: 1,
    name: "Star Charts Pro",
    description: "Interactive star charts and celestial mapping",
    longDescription: "Star Charts Pro is a comprehensive tool for amateur and professional astronomers. It provides detailed, interactive star charts and celestial mapping capabilities, allowing users to explore the night sky with unprecedented detail and accuracy.",
    price: "$19.99",
    image: "/placeholder.svg?height=400&width=600",
    category: "Planetarium",
    subcategory: "Star Charts",
    rating: 4.5,
    downloads: 10000,
    version: "2.1.0",
    lastUpdated: "2023-11-15",
    developer: "AstroSoft Inc.",
    requirements: ["Windows 10 or later", "4GB RAM", "1GB free disk space"],
    tags: ["star charts", "celestial mapping", "interactive"],
    installed: false,
    reviews: []
  },
  {
    id: 2,
    name: "Telescope Control Suite",
    description: "Advanced mount control and tracking capabilities",
    longDescription: "Telescope Control Suite offers precise control over various telescope mounts. It features advanced tracking algorithms, support for multiple mount types, and integration with popular astronomy software.",
    price: "$29.99",
    image: "/placeholder.svg?height=400&width=600",
    category: "Hardware",
    subcategory: "Telescope Control",
    rating: 4.8,
    downloads: 5000,
    version: "3.0.2",
    lastUpdated: "2023-12-01",
    developer: "SkyTech Solutions",
    requirements: ["Windows/Mac/Linux", "2GB RAM", "USB 2.0 port"],
    tags: ["telescope", "mount control", "tracking"],
    installed: true,
    reviews: []
  },
  {
    id: 3,
    name: "Deep Sky Imager",
    description: "Astrophotography image processing and stacking",
    longDescription: "Deep Sky Imager is a powerful tool for processing and stacking astrophotography images. It includes advanced algorithms for noise reduction, star alignment, and color calibration.",
    price: "$39.99",
    image: "/placeholder.svg?height=400&width=600",
    category: "Imaging",
    subcategory: "Image Processing",
    rating: 4.7,
    downloads: 7500,
    version: "2.3.1",
    lastUpdated: "2023-10-20",
    developer: "AstroPixel",
    requirements: ["Windows 10 or later", "8GB RAM", "2GB free disk space", "OpenCL compatible GPU"],
    tags: ["astrophotography", "image processing", "stacking"],
    installed: false,
    reviews: []
  },
  {
    id: 4,
    name: "Planetary Analyzer",
    description: "Detailed analysis tools for planetary observation",
    longDescription: "Planetary Analyzer provides a suite of tools for studying and analyzing planets in our solar system. Features include surface mapping, atmospheric analysis, and historical data comparison.",
    price: "Free",
    image: "/placeholder.svg?height=400&width=600",
    category: "Analysis",
    subcategory: "Planetary",
    rating: 4.2,
    downloads: 15000,
    version: "1.5.0",
    lastUpdated: "2023-09-05",
    developer: "Solar System Sciences",
    requirements: ["Any modern web browser"],
    tags: ["planets", "analysis", "solar system"],
    installed: true,
    reviews: []
  },
  {
    id: 5,
    name: "Comet Tracker",
    description: "Real-time comet tracking and prediction",
    longDescription: "Comet Tracker allows astronomers to track and predict the paths of known comets. It includes a database of historical comet data and provides tools for calculating future positions and visibility windows.",
    price: "$9.99",
    image: "/placeholder.svg?height=400&width=600",
    category: "Tracking",
    subcategory: "Comets",
    rating: 4.6,
    downloads: 3000,
    version: "1.2.3",
    lastUpdated: "2023-11-30",
    developer: "Orbital Dynamics Ltd.",
    requirements: ["Windows/Mac/Linux", "4GB RAM", "Internet connection"],
    tags: ["comets", "tracking", "prediction"],
    installed: false,
    reviews: []
  }
]

